 
                    <a class="item" href="https://embedthis.com/">Embedthis</a>
                    <a class="item" href="https://embedthis.com/esp/">ESP Site</a>
                    <a class="item" href="http://goo.gl/66rlSc">ESP News</a>
                    <a class="item" href="https://github.com/embedthis/esp">Repository</a>
                    <a class="item" href="https://embedthis.com/blog/">Blog</a>
                    <a class="item" href="https://twitter.com/mobstream">Twitter</a>
